name: Build ClassIsland Guardian
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-2022
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
            
            - name: Install dependencies
              run: pip install pyinstaller && pip install -r src\requirements.txt

            - name: Build Python Executable
              run: |
                pyinstaller --distpath app\appdata -w -n guardian src\guardian.py
                pyinstaller --distpath app\appdata -w -n config src\config.py
                pyinstaller --distpath app -n setup src\setup.py

            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v2
            
            - name: Build Driver Executable
              run: msbuild drivers\drivers.slnx /p:Configuration=Release /p:Platform=x64 /p:OutputPath=app\drivers

            - name: Create test certificate
              run: |
                $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=Guardian Test" -CertStoreLocation Cert:\CurrentUser\My
                Export-Certificate -Cert $cert -FilePath guardian_test.cer
              shell: powershell

            - name: Sign executables
              run: |
                for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do set VS=%%i
                call "%VS%\Common7\Tools\VsDevCmd.bat" -arch=x64
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\appdata\guardian\guardian.exe
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\appdata\config\config.exe
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\setup\setup.exe
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\drivers\file.sys
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\drivers\process.sys
                signtool sign /v /s My /n "Guardian Test" /fd SHA256 /t http://timestamp.digicert.com app\drivers\registry.sys
              shell: cmd

            - name: Build launcher Executable
              run: msbuild launcher\launcher.slnx /p:Configuration=Release /p:Platform=x64 /p:OutputPath=app\appdata

            - name: Create ZIP Archive
              run: powershell Compress-Archive -Path app\* -DestinationPath build.zip
            
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: build.zip
